version: "3.3"

networks:
  reverse_proxy:
    external: true
    name: reverse_proxy

services:
  web:
    build: .
    container_name: easilok-blog
    restart: unless-stopped
    networks:
      - default
      - reverse_proxy
